name: adventure_nepal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  responsive_sizer: ^3.1.1
  intl: ^0.18.1
  palette_generator: ^0.3.3+2
  google_maps_flutter: ^2.3.1
  flutter_google_places: ^0.3.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_html: ^2.1.2
  geolocator: ^9.0.2
  http_interceptor: ^1.0.2
  get_storage: ^2.1.1
  otp_text_field: ^1.1.3
  url_launcher: ^6.1.14


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/places/
    - assets/images/launcher_icon.png

