name: adventure_nepal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons:
  get: ^4.6.6
  flutter:
    sdk: flutter
  responsive_sizer:
  intl:
  palette_generator:
  google_maps_flutter:
  flutter_google_places:
  flutter_staggered_grid_view:
  flutter_html:
  geolocator:
  http_interceptor:
  get_storage:
  otp_text_field:
  url_launcher:


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/places/
    - assets/images/launcher_icon.png

